---
- apt_repository:
    repo: 'ppa:linbit/linbit-drbd9-stack'
    state: present
- shell: test -d /mnt/persist/etc/drbd.d || cp -a /etc/drbd.d /mnt/persist/etc/ || mkdir /mnt/persist/etc/drbd.d
- mount:
    src: /mnt/persist/etc/drbd.d
    path: /etc/drbd.d
    fstype: none
    opts: bind
    state: mounted
- apt:
    name: drbd-dkms,drbd-utils,python-drbdmanage
    state: present
- blockinfile:
    path: /etc/drbdmanaged.cfg
    block: |
      drbdctrl-vg = lc
      storage-plugin = drbdmanage.storage.lvm_thinlv.LvmThinLv
      [Plugin:ThinLV]
      volume-group = lc
      pool-name = PoolDefault
- shell: test -f /etc/drbd.d/drbdctrl.res || drbdmanage init -q && sleep 5
